### ISSUE TITLE
错别字好多啊

### ISSUE THREAD

**Issue by chismxna** [GuoJing/linux-kernel-architecture#1]
这些个页面错字和笔误好多啊...
http://guojing.me/linux-kernel-architecture/posts/system-paging-unit/
位---为
是---时
南都----难度
用图----用途
......
http://guojing.me/linux-kernel-architecture/posts/system-hardware-cache-and-tlb/
成都----程度
从到----存到
没一个----每一个
缓冲期----缓冲器

http://guojing.me/linux-kernel-architecture/posts/physical-memory/
刘改----留给

http://guojing.me/linux-kernel-architecture/posts/thread-page-table-and-kernel-page-table/
页是----也是
收到----受到

http://guojing.me/linux-kernel-architecture/posts/pglist-data-and-zone/
变好----编号
氛围----分为
再-------在

http://guojing.me/linux-kernel-architecture/posts/kernel-preemption/
顺序所----顺序锁

都是输入法惹的祸

**Comment by GuoJing** [comment]
提 MR 吧。
